### ISSUE TITLE
facing issue while compiling buildroot for riscv architecure

### ISSUE THREAD

**Issue by billasurendra** [fernandotcl/TinyEMU#5]
Dear all,

I am trying to compile buildroot for riscv64, but I am getting many errors. I don't know how to resolve this error.

Error:

fseeko.c:109:4: error: #error "Please port gnulib fseeko.c to your platform! Loo k at the code in fseeko.c, then report this to bug-gnulib."
109 | #error "Please port gnulib fseeko.c to your platform! Look at the code in fseeko.c, then report this to bug-gnulib."
| ^~~~~
make[5]: *** [Makefile:1842: fseeko.o] Error 1
make[5]: *** Waiting for unfinished jobs....
freadahead.c: In function 'freadahead':
freadahead.c:91:3: error: #error "Please port gnulib freadahead.c to your platfo rm! Look at the definition of fflush, fread, ungetc on your system, then report this to bug-gnulib."
91 | #error "Please port gnulib freadahead.c to your platform! Look at the d efinition of fflush, fread, ungetc on your system, then report this to bug-gnuli b."
| ^~~~~
make[5]: *** [Makefile:1842: freadahead.o] Error 1
make[4]: *** [Makefile:1602: all] Error 2
make[3]: *** [Makefile:1506: all-recursive] Error 1
make[2]: *** [Makefile:1461: all] Error 2
make[1]: *** [package/pkg-generic.mk:198: /home/billa/buildroot-riscv-2018-10-20 /output/build/host-m4-1.4.17/.stamp_built] Error 2
make: *** [Makefile:36: _all] Error 2

Can any one please help me regarding above error.

Thanks in advance
Billa

**Comment by fernandotcl** [comment]
You might want to contact the buildroot community instead.
