### ISSUE TITLE
Adding x86_64 support

### ISSUE THREAD

**Issue by lonnietc** [fernandotcl/TinyEMU#6]
Hello,

I am digging around VMM's and came a cross Fabrice's TinyEMU which led me to yours.

I am wondering what it might take to add in support for x86_64?

Currently it can run:

32/64/128-bit RISC-V 
3-bit  Windows/Linux

Now I would like to to be able to emulate for 

64-bit Linux/Windows as well

Any thoughts on this?

**Comment by fernandotcl** [comment]
Hi! That would be an enormous amount of effort, sorry.

**Comment by lonnietc** [comment]
Thanks for responding to my inquiry about this.
